name: Build and Push Multi-Arch Container

env:
  REGISTRY_HOST: codeberg.org
  REGISTRY_REPO: gigirassy/pinata

on:
  workflow-dispatch:

jobs:
  build:
    runs-on: nune-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform building)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_REPO }}:latest